# This is a basic workflow to help you get started with Actions

name: Pytests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: verona  # This will create and activate the environment
          python-version: "3.10"  
          auto-activate-base: false
  
      - name: Install uv
        run: |
          conda run -n verona pip install uv
  
      - name: Install dependencies with uv
        run: |
          conda run -n verona uv pip install -r requirements.txt
  
      - name: Install local package
        run: |
          conda run -n verona uv pip install -e .
          
      - name: Install pytest, pytest-mock and pytest-cov
        run: |
          conda run -n verona uv pip install pytest pytest-mock pytest-cov
  
      - name: Run pytest
        run: |
          conda run -n verona python -m pytest --cov tests/ --verbose
